airqualitysite/airqualitysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('frontend/', include('frontend.urls')),
    path('', include('aqi.urls'))
]

airqualitysite/aqi/urls.py
from django.urls import path

from . import views

app_name = 'aqi'

urlpatterns = [
    path('', views.LocationForm.as_view(), name='location_form'),
    path('measurements', views.measurements, name='measurements'),
    path('ajax/load_cities', views.load_cities, name='ajax_load_cities'),
    path('ajax/load_locations', views.load_stations, name='ajax_load_locations'),
    path('populate', views.populate, name='populate_data'),

]

airqualitysite/frontend/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index)
]

airqualitysite/aqi/models.py
from django.db import models


# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=50, unique=True)
    code = models.CharField(max_length=3, editable=False, primary_key=True)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Station(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


class Location(models.Model):
    station = models.ForeignKey(Station, on_delete=models.SET_NULL, null=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

airqualitysite/frontend/models.py
from django.db import models

# Create your models here.

airqualitysite/aqi/forms.py
from django import forms

from .models import City, Location, Station


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ('country', 'city', 'station')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['city'].queryset = City.objects.none()
        self.fields['station'].queryset = Station.objects.none()

airqualitysite/aqi/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView

from . import forms
from .fetch import get_data
from .models import Location, City, Station, Country
from .populate import populate_stations

from rest_framework import generics
from .serializer import Serializer

# Create your views here.


# testing view...
class ListCreate(generics.ListCreateAPIView):
    queryset = Country.objects.all()
    serializer_class = Serializer
# ...............


class LocationForm(CreateView):
    model = Location
    form_class = forms.LocationForm


def get_location(request):
    if request.method == 'POST':
        form = forms.LocationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data.values()
            print(data, type(data))
            return HttpResponse(str(data))
        else:
            return HttpResponse('Invalid Form data')
    else:
        return HttpResponse('No post data')


def load_cities(request):
    print('loading cities')
    country_code = request.GET.get('country')
    cities = City.objects.filter(country=country_code).order_by('name')
    return render(request, 'aqi/city_dropdown.html', {'cities': cities})


def load_stations(request):
    print('loading stations')
    city_pk = request.GET.get('city')
    stations = Station.objects.filter(city=city_pk).order_by('name')
    return render(request, 'aqi/station_dropdown.html', {'stations': stations})


def populate(request):
    return populate_stations(request)


def measurements(request):
    req = request.POST
    city = get_object_or_404(City, pk=req['city'])
    station = get_object_or_404(Station, pk=req['station'])

    params = 'country={COUNTRY}&city={CITY}&location={STATION}'.format(
        COUNTRY=req['country'], CITY=city.name, STATION=station.name)
    print(params)

    data = get_data('latest', params)
    print(data)
    return render(request, 'aqi/measurements.html', {'data': data})

airqualitysite/frontend/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'frontend/index.html')

airqualitysite/aqi/templates/aqi/city_dropdown.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

airqualitysite/aqi/templates/aqi/location_form.html
<form method="post" id='locationForm' city_data_url="{% url 'aqi:ajax_load_cities' %}"
      location_data_url="{% url 'aqi:ajax_load_locations' %}"
      action="{% url 'aqi:measurements' %}" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
      $("#id_country").change(function () {
    var url = $("#locationForm").attr("city_data_url");
    var countryId = $(this).val();

    $.ajax({
      url: url,
      data: {
        'country': countryId
      },
      success: function (data) {
        $("#id_city").html(data);
      }
    });
  });

  $("#id_city").change(function () {
    var url = $("#locationForm").attr("location_data_url");
    var cityId = $(this).val();
    $.ajax({
      url: url,
      data: {
        'city': cityId
      },
      success: function (data) {
        $("#id_station").html(data);
      }
    });
  });


</script>

airqualitysite/aqi/templates/aqi/measurements.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Measurements</title>
</head>
<body>
    <a href="/">Home</a>
    <br>
    {% if data %}
    <table>
        <tr>
            <th>Pollutant</th>
            <th>Amount</th>
        </tr>
        {% for key, value in data.items %}
        <tr>
            <td>{{key}}</td>
            <td>{{value}}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</body>
</html>

airqualitysite/aqi/templates/aqi/station_dropdown.html
<option value="">---------</option>
{% for station in stations %}
<option value="{{ station.pk }}">{{ station.name }}</option>
{% endfor %}

airqualitysite/frontend/templates/frontend/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css">
  <title>aqi</title>
</head>
<body>
  <section class="section">
    <div class="container">
          <div id="app" class="columns"></div>
    </div>
  </section>
</body>
{% load static %}
<script src="{% static "frontend/main.js" %}"></script>
</html>